% Different derivation of competition coefficients for Tilman R* model

Georges Kunstler


# Fitness
Let define the fitness of a mutant with trait $x_i$ and of density
$N_I$ in competition with a resident with trait $x_R$ and of density $N_R$ as:

\begin{equation}
f(x_I, x_R, N_I, N_R) = \frac{dN_I}{dt} \, \frac{1}{N_I}
\end{equation}

## The three different estimation of competition kernel

All the derivation of competition kernel from Abrams et al. (2008),
Abrams (1987) and Tilman (1982) all fall in one these three kernels.

### Abrams et al. 2008
Abrams et al. (2008) define three different estimation of competition
kernels.

* Comparing equilibrium density of species allopatry or in sympatry.

\begin{equation}
\alpha_{IR} = \frac{N_{IA} - N_{IS}}{N_{RS}}
\end{equation}

This index is equivalent to the approach taken by Tilman (1982) in
chapter 7 as he was deriving the competition kernel from $N_{IA}$,
$N_{IS}$, and $N_{RS}$.

* Derivate of fitness at equilibrium.

\begin{equation}
\beta_{IR} = \frac{\partial f(x_I, x_R, N_I, N_R) / \partial
N_R}{\partial f(x_I, x_R, N_I, N_R) / \partial N_Y} \bigg|
_{N_I=N_{IS};N_R=N_{RS}}
\end{equation}

This is equivalent to
comp[etition kernel derivated in Abrams (1987), for a modified version of Tilman R* at equilibrium.

* Derivate of fitness for a rare invider (I'm just presenting the $\chi^*$)

\begin{equation}
\chi_{IR} = \frac{\partial f(x_I, x_R, N_I, N_R) / \partial
N_R}{\partial f(x_I, x_R, N_I, N_R) / \partial N_I} \bigg|
_{N_I=0;N_R=N_{RA}}
\end{equation}

# Comparison of Lotka Volterra and R* model at equilibrium
This is based on the Chapter 7 of Tilman 1982. The basic idea of the chapter 7 of Tilman is to take the R* model at
equilibrium and rework out the equation to match the same structure as
these two equations and see what match $K$ and $\alpha$, so as $\alpha_{ij}$ in Abrams et al. (2008).

## R* model based on Huisman & Weissing equations:

Here I follow the notation of Huisman & Weissing (2001) because this is what we have used so far. This is different from Tilman chapter 7.

\begin{equation}
\frac{dN_i}{dt} \, \frac{1}{N_i}=   (\min(p_{1i}(R_1), p_{2i}(R_2))-m)
\end{equation}

\begin{equation}
\frac{dR_j}{dt} = D \times (S_j-R_j) - \sum_{i=1}^I {C_{ji} N_i
\min(p_{1i}(R_1),p_{2i}(R_2))}
\end{equation}

\begin{equation}
p_{ji}(R_j) = \frac{r R_j}{K_{ji}+R_j}
\end{equation}

j and i in 1, 2.

We assume $D=m$.

A species $i$ is defined by two vectors of parameters (of length two for two resources):
- $K_{\bullet i}$ which is the half saturation constant for each resource ($K_{1i}$ for resource $R_1$ and $K_{2i}$ for resource $R_2$).
- $C_{\bullet i}$ which is the consumption rate (or the content of nutriment) for each resource ($C_{1i}$ for resource $R_1$ and $C_{2i}$ for resource $R_2$).

The resource requirement of species $i$ is defined by:
$R_{11}^* = \frac{m K_{11}}{r-m}$

I assume that species 1 as the minimum $R^*$ for $R_1$ and species 2 for $R_2$.

## Equilibrium for R*

At equilibrium $\frac{dN}{dt} = 0$ and $\frac{dR}{dt} = 0$.

$\min(p_{1i}(R_1), p_{2i}(R_2)) = m$.

### If $R_1$ is the limiting factor for both species

$N_{1A}$ is defined as the equilibrium population when
single species. Which is:

$0 = D(S_1 - R_{11}^*) - C_{11} \bar{N_1} m$

with
$R_{11}^* = \frac{m K}{r-m}$

Thus $N_{1A}$ equilibrium for single species case is:
$\bar{N_{1A}} = \frac{(S_1 - R_{11}^*)}{C_{11}}$

#### Equilibrium with two species

$\bar{N_{1S}} = \frac{S_1-R_{11}^*}{C_{11}} - \frac{C_{12}}{C_{11}} \times \bar{N_{2S}}$

$\bar{N_{1S}} = N_{1A} - \frac{C_{12}}{C_{11}} \times \bar{N_{2S}}$

Thus

$\alpha_{21} = \frac{C_{12}}{C_{11}}$

In the same way:


$\alpha_{12} = \frac{C_{11}}{C_{12}}$

### If $R_2$ is the limiting factor for both species

Applying the same approach as for when $R_1$ is limiting gives:

$\alpha_{21} = \frac{C_{22}}{C_{21}}$

and

$\alpha_{12} = \frac{C_{21}}{C_{22}}$

### If $R_1$ is the limiting factor for species 1 and $R_2$ for species 2.

Applying the same approach as for when $R_1$ is limiting gives:

$\alpha_{21} = \frac{C_{12}}{C_{11}}$

In the same way:

$\alpha_{12} = \frac{C_{21}}{C_{22}}$

### Determining when $R_1$ or $R_2$ are limiting?

For the species 1 the boundary between case where the species is limited by $R_1$ or $R_2$ is given by:
$\frac{(S_2 - R_{21}^*)}{C_{21}} = \frac{(S_1 - R_{11}^*)}{C_{11}}$

If the first part is smaller than the second part of the previous equation then $R_2$ limited if inverse $R_1$ limited.

If we develop for $R^*$ this gives:
$\frac{(S_2 - \frac{m K'_{21}}{r -m})}{C_{21}} = \frac{(S_1 - \frac{m K'_{11}}{r-m})}{C_{11}}$

To start to explore what kind of shape of competition would be predicted by these equations I will assume that a species is defined by a trait $x$ with $K_{1i} =C_{1i} = x$ and $K_{2i} = C_{2i} = 1 - x$.

Replacing $K$ and $C$ in the previous equation give the condition for $R_2$ limiting depending on $S_1, S_2$ and $x$.

Thus a species defined by the trait $x$ is $R_2$ limited if

$\frac{S_2}{S_1} < \frac{1-x}{x}$ and $R_1$ limited if inverse.

## Estimation with the $\beta_{ij}$ of Abrams (1987)

Abrams assume that resources are at their equilibrium values $R_j^*$. Based on this assumption the four differential equations of the R* model can be simplified to only two.

\begin{equation}
\frac{dN_1}{dt} \, \frac{1}{N_1}=   (\min(p_{11}(R_1), p_{21}(R_2^*))-m)
\end{equation}

\begin{equation}
\frac{dN_2}{dt} \, \frac{1}{N_2}=   (\min(p_{12}(R_1), p_{22}(R_2^*))-m)
\end{equation}

If 1 and 2 are limited per resource $R_1$, then

\begin{equation}
\beta_{12} = \frac{\partial R_1^* / \partial
N_2}{\partial R_1^* / \partial N_1}
\end{equation}

Implicit differentiation of

\begin{equation}
\frac{dR_1}{dt} = 0 = D \times (S_1-R_1^*) - \sum_{i=1}^I {C_{ji} N_i
p_{1i}(R_1^*)}
\end{equation}

gives

\begin{equation}
\frac{\partial R_1^*}{\partial N_2} = \frac{C_{12}}{K_{12}+R_1^*}
\end{equation}

and

\begin{equation}
\frac{\partial R_1^*}{\partial N_1} = \frac{C_{11}}{K_{11}+R_1^*}
\end{equation}

Thus

\begin{equation}
\beta_{12} = \frac{C_{12} \, (K_{11} + R_1^*) }{c_{11} \, (K_{12} + R_1^*)}
\end{equation}


If 1 has lower $R_1^*$ then replace in previous function, and we assume that a species is defined by a trait $x$ with $K_{1i} =C_{1i} = x$ and $K_{2i} = C_{2i} = 1 - x$.

Then

\begin{equation}
\beta_{12} = \frac{x_2 \, r}{x_2 \, (r-m) +m \, x_1}
\end{equation}

NEED TO FINISH FROM HERE BY WORKING ALL CASES OF WHICH RESOURCES IS LIMITING FOR WHICH SPECIES AND WHICH SPECIES HAS LOWER R* BASED ON TRAITS X. THIS WILL GIVES THE COMPETITION KERNEL.

\pagebreak

## R function to plot $\alpha$ and $\beta$ as functions of $x$

With the trait x of species 1 varying from 0 to 1 and the species 2 fixed at x = 0.4.

```{r Tilman_alpha, echo = FALSE, results="asis", fig.cap = "Tilman derivation of alpha"}

K.and.alpha.in.fun.x <- function(x, xp, m = 0.25, r = 1, S.1 = 1, S.2 = 1){
  x.R.2.lim.TF   <- (S.2/S.1) < ((1-x)  / x)
  xp.R.2.lim.TF <- (S.2/S.1) < ((1-xp)/ xp)
  if (x.R.2.lim.TF) {
	  K.x <- (S.2 - m*(1-x)/(r-m))/(1-x)
	  alpha.xp.x <- (1-xp)/(1-x)
  }else{
	  K.x <- (S.1 - m*(x)/(r-m))/(x)
	  alpha.xp.x <- (xp)/(x)
  }
  #species x.p
  if (xp.R.2.lim.TF) {
	  K.xp <- (S.2 - m*(1-xp)/(r-m))/(1-xp)
	  alpha.x.xp <- (1-x)/(1-xp)
  }else{
	  K.xp <- (S.1 - m*(xp)/(r-m))/(xp)
	  alpha.x.xp <- (x)/(xp)
  }
  return(data.frame(K.x = K.x, K.xp = K.xp,
                    alpha.xp.x = alpha.xp.x, alpha.xp.x = alpha.xp.x))
}

x.vec <- (1:99)/100

xp.fix <- 0.4
K.alpha <- do.call('rbind', lapply(x.vec, K.and.alpha.in.fun.x , xp =xp.fix))

par(mfrow = c(2,2))
plot(x.vec, K.alpha[['alpha.xp.x']], type ='l',
     xlab = 'trait x',
	 ylab = expression(paste(alpha[12])))
plot(x.vec, K.alpha[['K.x']], type ='l',
     xlab = 'trait x', ylab = expression(K[1]))
plot(x.vec, K.alpha[['alpha.x.xp']], type ='l',
     xlab = 'trait x', ylab = expression(paste(alpha[21])))
plot(x.vec, K.alpha[['K.xp']], type ='l',
     xlab = 'trait x', ylab = expression(K[2]))
```


# References

* Abrams, Peter A. 1987. “The Nonlinearity of Competitive Effects in Models of Competition for Essential Resources.” Theoretical Population Biology 32 (1): 50–65. doi:10.1016/0040-5809(87)90039-6.
* Abrams, Peter A., Claus Rueffler, and Russell Dinnage. 2008. “Competition-Similarity Relationships and the Nonlinearity of Competitive Effects in Consumer-Resource Systems.” The American Naturalist 172 (4): 463–74. doi:10.1086/590963.
* Huisman, J., and Weissing, F.J. (2001). Biological conditions for oscillations and chaos generated by multispecies competition. Ecology 82, 2682–2695.
* Tilman, D. (1982) Resource Competition and Community Structure. Princeton University Press, Princeton, NJ.
* Tilman, David. 1987. “Further Thoughts on Competition for Essential Resources.” Theoretical Population Biology 32 (3): 442–46.
