## # Simple models and competition

## Note that the wiki version of this file is generated by the R file
## in the repository.  Changes will be manually ported over, but will
## be preserved in the history at least.

## Note also that these are rough working notes more than anything
## resembling a finished analysis.

### TODO:
### * Subtraction approach for the simple models.

## The idea here is to see if we can infer the shape of competition
## from simple models.  I'm trying this on two types of models:
##
## * Models with *explicit* competition, where the competition
##   "kernel" is given as an ingredient of the model and is therefore
##   known.
## * Models with *implicit* competition, where competition emerges
##   from the model, for example through the shared use of a
##   resource.

## There are a number of live issues that I'm unresolved about how to
## deal with:
##
## 1. Are we interested in measuring competition *exerted* (species X
##    depresses how much species Y are capable of growing) or in
##    competition *felt* (species X's growth is depressed by species
##    Y).  In both is that X is the "focal" species and exists at
##    nontrivial density, while Y is something that we want to
##    evaluate at any point along a trait axis.
## 2. Indirect competition and second order effects.  As a result
##    mostly considering single resident cases at the moment.

## I'm skeptical that we can come up with one "true" measure of
## competition.  What I am hoping to be able to do is to describe
## competition *qualitatively*
##
## * is it symmetric or asymmetric?
## * is it linear with respect to population density?  sublinear or
##   superlinear?

## The basic approach is centred around the idea that we should be
## able to get a handle on competition by looking to see how
## performance of one species varies with the density of another.  So
## if we increase a resident species' density slightly, then if mutant
## fitness decreases a lot then the resident has a strong competitive
## effect on the mutant (so this is competition *exerted* by the
## mutant)

## # Explicit competition

## There are two models here: Dieckmann and Dobeli 1999 and Kisdi
## 1999.  Both these models are related to Lotka Volterra models with
## continuous competition functions that vary as a function of species
## traits rather than being particular to a species.  The species
## competitive effect scales linearly with density.

## * [Dieckmann and Dobeli 1999](simple_models_dieckmann)
## * [Kisdi 1999](simple_models_kisdi)

## # Implicit competition

## This is where things get more interesting.

## * [Rstar, 1 resource](simple_models_rstar_1)
## * [Rstar, 2 resources](simple_models_rstar_2)

## # Scaling factors

## Fitness is defined as the *per capita rate of population increase*,
## that is -- the number of offspring per individual per unit time.
## This has units of individuals / (individuals time).
##
## Computing the derivative of this with respect to resident density
## changes the units by a factor of 1 / (resident density).

